// src/data/img-sizes.js is written by two pipelines — process-images.mjs for
// the full-size photographs and rescue-thumbs.mjs for the 206px rescues — so
// reading and writing it lives here, and each run merges into what the other
// left rather than replacing it.
import fs from 'node:fs';

export const SIZES_FILE = 'src/data/img-sizes.js';

export const readSizes = () => {
  if (!fs.existsSync(SIZES_FILE)) return {};
  const body = fs.readFileSync(SIZES_FILE, 'utf8');
  const out = {};
  for (const m of body.matchAll(/"([^"]+)":\s*\{\s*w:\s*(\d+),\s*h:\s*(\d+),\s*sm:\s*(\d+)\s*\}/g)) {
    out[m[1]] = { w: +m[2], h: +m[3], sm: +m[4] };
  }
  return out;
};

export const writeSizes = (sizes) => {
  // a picture that has been dropped from a manifest leaves its entry behind
  // otherwise, and the next run would merge it straight back in
  for (const k of Object.keys(sizes)) {
    if (!fs.existsSync(`public/img/${k}.webp`)) delete sizes[k];
  }
  const rows = Object.keys(sizes).sort()
    .map((k) => `  "${k}": { w: ${sizes[k].w}, h: ${sizes[k].h}, sm: ${sizes[k].sm} }`);
  fs.writeFileSync(SIZES_FILE, `// Generated by scripts/process-images.mjs and scripts/rescue-thumbs.mjs —
// do not edit by hand. w/h are the full-size file's real pixels, sm the width
// of its half-size sibling. srcset needs true widths or the browser hands a
// small file to a big slot and the picture looks soft; Shop The Room needs the
// shape, because its hotspots are percentages of the photograph.
export const IMG_SIZES = {
${rows.join(',\n')}
};
`, 'utf8');
  return rows.length;
};
